spring:
  cloud:
    stream:
      default-binder: msk
      kafka:
        binder:
          headerMapperBeanName: defaultKafkaHeaderMapper
          configuration:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.apache.kafka.common.serialization.StringSerializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      binders:
        msk:
          type: kafka
          clusterName: spring-msk-app
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: b-2.springmskapp.2r89de.c8.kafka.us-west-2.amazonaws.com:9098,b-1.springmskapp.2r89de.c8.kafka.us-west-2.amazonaws.com:9098,b-3.springmskapp.2r89de.c8.kafka.us-west-2.amazonaws.com:9098
                      auto-create-topics: true
                      configuration:
                        security:
                          protocol: SASL_SSL
                        sasl:
                          mechanism: AWS_MSK_IAM
                          jaas:
                            config: software.amazon.msk.auth.iam.IAMLoginModule required
                          client:
                            callback:
                              handler:
                                class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

      bindings:
        transferCompletedEvent-out-0:
          binder: msk
          producer:
            use-native-encoding: true
          destination: msk-topic

logging:
  level:
    org.apache.kafka: INFO
kafka:
  encoding:
    type: apache

